## A.I. Assignment 5

## Learning Goals

By the end of this lab, you should be able to:
* Get more familiar with tensors in pytorch 
* Create a simple multilayer perceptron model with pytorch
* Visualise the parameters


### Task

Build a fully connected feed forward network that adds two bits. Determine the a propper achitecture for this network (what database you use for this problem? how many layers? how many neurons on each layer? what is the activation function? what is the loss function? etc)

Create at least 3 such networks and compare their performance (how accurate they are?, how farst they are trained to get at 1 accuracy?)

Display for the best one the weights for each layer.


In [607]:
import torch
import torch.nn as nn
import torch.optim as optim
from collections import OrderedDict


print("\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~ MODEL 1 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n")

# add 2 bits
data_in1 = torch.tensor([[0, 0], [0, 1], [1, 0], [1, 1]]).float()   
data_target1 = torch.tensor([[0, 0], [0, 1], [0, 1], [1, 0]]).float()

# define the model architecture
model1 = nn.Sequential(
    nn.Linear(2,4),  # hidden 1 net layer
    nn.ReLU(),       # hidden 1 activation function
    nn.Linear(4,8),  # hidden 2 net layer
    nn.Tanh(),       # hidden 2 activation function
    nn.Linear(8,2),  # output net layer
    nn.Sigmoid())    # output activation layer

print("\n1) MODEL:\n\n", model1, "\n")
print("\n2) WEIGHTS:\n\n", model1[0].weight, "\n")
print("\n3) BIAS\n\n:", model1[0].bias, "\n")

# binary cross entropy
criterion1 = nn.MSELoss()  
optimizer1 = optim.SGD(model1.parameters(), lr=0.2)

# train the model
epochs = 1000

for epoch in range(epochs):
    # forward pass
    outputs1 = model1(data_in1) 
    # compute loss
    loss = criterion1(outputs1, data_target1) 
    # backward pass and optimize
    optimizer1.zero_grad()
    loss.backward()
    optimizer1.step()
    # progress
    if (epoch + 1) % 100 == 0:
        print(f'epoch {epoch+1}/{epochs}, loss {loss.item():.4f}')
        


~~~~~~~~~~~~~~~~~~~~~~~~~~~~ MODEL 1 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~


1) MODEL:

 Sequential(
  (0): Linear(in_features=2, out_features=4, bias=True)
  (1): ReLU()
  (2): Linear(in_features=4, out_features=8, bias=True)
  (3): Tanh()
  (4): Linear(in_features=8, out_features=2, bias=True)
  (5): Sigmoid()
) 


2) WEIGHTS:

 Parameter containing:
tensor([[ 0.3032, -0.5200],
        [ 0.4107,  0.0429],
        [-0.1178,  0.1088],
        [ 0.1954,  0.3312]], requires_grad=True) 


3) BIAS

: Parameter containing:
tensor([-0.4921,  0.1223,  0.3745, -0.3408], requires_grad=True) 

epoch 100/1000, loss 0.2160
epoch 200/1000, loss 0.1945
epoch 300/1000, loss 0.1498
epoch 400/1000, loss 0.1149
epoch 500/1000, loss 0.0891
epoch 600/1000, loss 0.0567
epoch 700/1000, loss 0.0277
epoch 800/1000, loss 0.0143
epoch 900/1000, loss 0.0086
epoch 1000/1000, loss 0.0059


In [611]:
import torch
import torch.nn as nn
import torch.optim as optim
from collections import OrderedDict

print("\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~ MODEL 2 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n")

# add 2 bits
data_in2 = torch.tensor([[0, 0], [0, 1], [1, 0], [1, 1]]).float()
data_target2 = torch.tensor([[0, 0], [0, 1], [0, 1], [1, 0]]).float()

# define the model architecture
model2 = nn.Sequential(
    nn.Linear(2,4),  # input layer
    nn.Tanh(),       # activation function
    nn.Linear(4,8),  # 1st hidden layer
    nn.ReLU(),       # activation function
    nn.Linear(8,2),  # 2nd hidden layer
    nn.Sigmoid())    # output layer

print("\n1) MODEL:\n\n", model2, "\n")
print("\n2) WEIGHTS:\n\n", model2[0].weight, "\n")
print("\n3) BIAS\n\n:", model2[0].bias, "\n")

# binary cross entropy
criterion2 = nn.MSELoss()
optimizer2 = optim.SGD(model2.parameters(), lr=0.2)

epochs = 1000

for epoch in range(epochs):
    # forward pass
    outputs2 = model2(data_in2)
    # compute loss
    loss = criterion2(outputs2, data_target2) 
    # backward pass and optimize
    optimizer2.zero_grad() 
    loss.backward()
    optimizer2.step()
    # progress
    if (epoch+1)%100 == 0:
        print(f'epoch {epoch+1}/{epochs}, loss {loss.item():.4f}')



~~~~~~~~~~~~~~~~~~~~~~~~~~~~ MODEL 2 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~


1) MODEL:

 Sequential(
  (0): Linear(in_features=2, out_features=4, bias=True)
  (1): Tanh()
  (2): Linear(in_features=4, out_features=8, bias=True)
  (3): ReLU()
  (4): Linear(in_features=8, out_features=2, bias=True)
  (5): Sigmoid()
) 


2) WEIGHTS:

 Parameter containing:
tensor([[ 0.2325, -0.6786],
        [ 0.1892, -0.6246],
        [-0.5052, -0.4639],
        [-0.1895, -0.3681]], requires_grad=True) 


3) BIAS

: Parameter containing:
tensor([ 0.0953,  0.3031,  0.1317, -0.5862], requires_grad=True) 

epoch 100/1000, loss 0.2130
epoch 200/1000, loss 0.1946
epoch 300/1000, loss 0.1624
epoch 400/1000, loss 0.1277
epoch 500/1000, loss 0.0905
epoch 600/1000, loss 0.0491
epoch 700/1000, loss 0.0246
epoch 800/1000, loss 0.0133
epoch 900/1000, loss 0.0080
epoch 1000/1000, loss 0.0053


In [612]:
import torch
import torch.nn as nn
import torch.optim as optim
from collections import OrderedDict
import sklearn


print("\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~ MODEL 3 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n")

# add 2 bits
data_in3 = torch.tensor([[0, 0], [0, 1], [1, 0], [1, 1]]).float()
data_target3 = torch.tensor([[0, 0], [0, 1], [0, 1], [1, 0]]).float()

# define the model architecture
model3 = nn.Sequential(
    nn.Linear(2,4),  # input layer
    nn.Sigmoid(),    # activation function
    nn.Linear(4,8),  # 1st hidden layer
    nn.Sigmoid(),    # activation function
    nn.Linear(8,2),  # 2nd hidden layer
    nn.Sigmoid())    # output layer

print("\n1) MODEL:\n\n", model3, "\n")
print("\n2) WEIGHTS:\n\n", model3[0].weight, "\n")
print("\n3) BIAS\n\n:", model3[0].bias, "\n")

# binary cross entropy
criterion3 = nn.MSELoss()
optimizer3 = optim.SGD(model3.parameters(), lr=0.2)

epochs = 1000

for epoch in range(epochs):
    # forward pass
    outputs3 = model3(data_in3)
    # compute loss
    loss = criterion3(outputs3, data_target3)
    # backward pass and optimize
    optimizer3.zero_grad()
    loss.backward()
    optimizer3.step()
    # progress
    if (epoch + 1) % 100 == 0:
        print(f'Finished epoch {epoch+1}/{epochs}, latest loss {loss.item():.4f}')


~~~~~~~~~~~~~~~~~~~~~~~~~~~~ MODEL 3 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~


1) MODEL:

 Sequential(
  (0): Linear(in_features=2, out_features=4, bias=True)
  (1): Sigmoid()
  (2): Linear(in_features=4, out_features=8, bias=True)
  (3): Sigmoid()
  (4): Linear(in_features=8, out_features=2, bias=True)
  (5): Sigmoid()
) 


2) WEIGHTS:

 Parameter containing:
tensor([[ 0.1804,  0.4059],
        [ 0.4299, -0.0257],
        [ 0.4136,  0.6199],
        [ 0.0187, -0.5793]], requires_grad=True) 


3) BIAS

: Parameter containing:
tensor([ 0.0380,  0.3416, -0.3091,  0.3283], requires_grad=True) 

Finished epoch 100/1000, latest loss 0.2194
Finished epoch 200/1000, latest loss 0.2189
Finished epoch 300/1000, latest loss 0.2189
Finished epoch 400/1000, latest loss 0.2188
Finished epoch 500/1000, latest loss 0.2187
Finished epoch 600/1000, latest loss 0.2186
Finished epoch 700/1000, latest loss 0.2185
Finished epoch 800/1000, latest loss 0.2184
Finished epoch 900/1000, latest loss 0.2183
Finished epoch 

In [613]:
# Accuracies

# model 1
accuracies1 = []
with torch.no_grad():
    outputs1 = model1(data_in1)
    predicted = (outputs1 >= 0.5).float()
    accuracy = (predicted == data_target1).float().mean()
    accuracies1.append(accuracy)
    print("\nAccuracy: {:.2f}%".format(accuracy.item() * 100))
    
# model 2
accuracies2 = []
with torch.no_grad():
    outputs2 = model2(data_in2)
    predicted = (outputs2 >= 0.5).float()
    accuracy = (predicted == data_target2).float().mean()
    accuracies2.append(accuracy)
    print("\nAccuracy: {:.2f}%".format(accuracy.item() * 100))
    
# model 3
accuracies3 = []
with torch.no_grad():
    outputs3 = model3(data_in3)
    predicted = (outputs3 >= 0.5).float()
    accuracy = (predicted == data_target3).float().mean()
    accuracies3.append(accuracy)
    print("\nAccuracy: {:.2f}%".format(accuracy.item() * 100))


Accuracy: 100.00%

Accuracy: 100.00%

Accuracy: 62.50%
