In [1]:
import numpy as np

In [2]:
my_array = np.array([1, 2, 3, 4])     # works as it wouldwith standard list
len(my_array)

4

In [3]:
# The shape array of an array is very useful (we’ll see more of it later when we talk about 
# 2D arrays – matrices – and higher-dimensional arrays).

my_array.shape

(4,)

In [4]:
# Numpy arrays are typed. This means that by default, all the elements will be assumed to 
# be of the same type (e.g., integer, float, String).

my_array.dtype

dtype('int64')

In [6]:
# Numpy arrays have similar functionality as lists! Below, we compute the length, slice the array,
# and iterate through it (one could identically perform the same with a list).

print(len(my_array))
print(my_array[2:4])

for element in my_array:
    print(element)

4
[3 4]
1
2
3
4


In [7]:
# There are two ways to manipulate numpy arrays:
#    1. by using the numpy module's methods (e.g., np.mean())
#    2. by applying the function np.mean() with the numpy array as an argument.

print(my_array.mean())
print(np.mean(my_array))

2.5
2.5


In [8]:
# There are many other efficient ways to construct numpy arrays. Here are some commonly used
# numpy array constructors. Read more details in the numpy documentation.

np.ones(10)    # generates 10 floating point ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [9]:
# Numpy gains a lot of efficiency from being typed. That is, all elements in the array have the same type,
# such as integer or floating point. The default type, as it can be seen above, is a float.
# (Each float uses either 32 or 64 bits of memory, depending on if the code is running a 32-bit or 64-bit 
# machine, respectively).

np.dtype(float).itemsize    # in bytes (remember, 1 byte = 8 bits)

8

In [10]:
np.ones(10, dtype='int')    # generates 10 integer ones

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [11]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
# Often, you will want random numbers. Use the random constructor!

np.random.random(10)    # uniform from [0,1]

array([0.68546353, 0.46697714, 0.69739225, 0.9707207 , 0.20422881,
       0.94750071, 0.53023885, 0.97525027, 0.00936551, 0.60081829])

In [17]:
# You can generate random numbers from a normal distributin with mean 0 and variance 1:

normal_array = np.random.rand(1000)
print("The sample mean and standard deviation are %f and %f, respectively. " %(np.mean(normal_array), np.std(normal_array)))

The sample mean and standard deviation are 0.490421 and 0.290187, respectively. 


In [18]:
len(normal_array)

1000

In [20]:
# You can sample with and without replacement from an array. Let's first construct a list with evenly-spaced values:

grid = np.arange(0., 1.01, 0.1)
grid

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [22]:
# Without replacement

np.random.choice(grid, 5, replace=False)

array([0. , 0.9, 0.2, 0.4, 0.1])

In [23]:
np.random.choice(grid, 20, replace=False)

ValueError: Cannot take a larger sample than population when 'replace=False'

In [24]:
# With replacement

np.random.choice(grid, 20, replace=True)

array([0.5, 0.6, 0.9, 0.5, 0.9, 0.2, 0.1, 0.7, 0.9, 1. , 0.2, 0.3, 0.2,
       0.4, 0.2, 0.9, 0.5, 0.5, 0.9, 0.1])

In [25]:
# Let's create 1,000 points between -10 and 10

x = np.linspace(-10, 10, 1000)       # linspace() returns evenly-spaced numbers over a specified interval
x[-5:], x[:5]

(array([ 9.91991992,  9.93993994,  9.95995996,  9.97997998, 10.        ]),
 array([-10.        ,  -9.97997998,  -9.95995996,  -9.93993994,
         -9.91991992]))